/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as HostRouteImport } from './routes/host'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicN8nCleaningRouteImport } from './routes/api/public/n8n/cleaning'
import { Route as ApiPublicN8nBookingRouteImport } from './routes/api/public/n8n/booking'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nCleaningRoute = ApiPublicN8nCleaningRouteImport.update({
  id: '/api/public/n8n/cleaning',
  path: '/api/public/n8n/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nBookingRoute = ApiPublicN8nBookingRouteImport.update({
  id: '/api/public/n8n/booking',
  path: '/api/public/n8n/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/host': typeof HostRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/n8n/booking': typeof ApiPublicN8nBookingRoute
  '/api/public/n8n/cleaning': typeof ApiPublicN8nCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/host': typeof HostRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/n8n/booking': typeof ApiPublicN8nBookingRoute
  '/api/public/n8n/cleaning': typeof ApiPublicN8nCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/host': typeof HostRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/api/public/n8n/booking': typeof ApiPublicN8nBookingRoute
  '/api/public/n8n/cleaning': typeof ApiPublicN8nCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/host'
    | '/matches'
    | '/onboarding'
    | '/api/public/n8n/booking'
    | '/api/public/n8n/cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/host'
    | '/matches'
    | '/onboarding'
    | '/api/public/n8n/booking'
    | '/api/public/n8n/cleaning'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/host'
    | '/matches'
    | '/onboarding'
    | '/api/public/n8n/booking'
    | '/api/public/n8n/cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HostRoute: typeof HostRoute
  MatchesRoute: typeof MatchesRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicN8nBookingRoute: typeof ApiPublicN8nBookingRoute
  ApiPublicN8nCleaningRoute: typeof ApiPublicN8nCleaningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/cleaning': {
      id: '/api/public/n8n/cleaning'
      path: '/api/public/n8n/cleaning'
      fullPath: '/api/public/n8n/cleaning'
      preLoaderRoute: typeof ApiPublicN8nCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/booking': {
      id: '/api/public/n8n/booking'
      path: '/api/public/n8n/booking'
      fullPath: '/api/public/n8n/booking'
      preLoaderRoute: typeof ApiPublicN8nBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HostRoute: HostRoute,
  MatchesRoute: MatchesRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicN8nBookingRoute: ApiPublicN8nBookingRoute,
  ApiPublicN8nCleaningRoute: ApiPublicN8nCleaningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
