// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient(): SupabaseClient<Database> {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = 
    import.meta.env.VITE_SUPABASE_ANON_KEY || 
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
    process.env.SUPABASE_ANON_KEY || 
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_ANON_KEY'] : []),
    ];
    // Loud, actionable message — this is almost always "the dev server was started
    // before .env was populated; restart it" rather than a missing file.
    const message =
      `[Supabase] Not configured — missing ${missing.join(', ')}. ` +
      `Sign-in/sign-up will not work. Fix: ensure these are in .env at the project root, ` +
      `then RESTART the dev server (Vite only reads .env at startup).`;
    console.error(message);
    if (typeof document !== 'undefined') {
      // Surface a visible banner in the browser so it isn't silently swallowed.
      queueMicrotask(() => {
        if (document.getElementById('supabase-config-banner')) return;
        const el = document.createElement('div');
        el.id = 'supabase-config-banner';
        el.textContent = 'Supabase not configured — restart the dev server (Vite reads .env only at startup).';
        el.style.cssText =
          'position:fixed;z-index:99999;left:0;right:0;bottom:0;padding:10px 14px;' +
          'background:#b91c1c;color:#fff;font:600 13px/1.4 system-ui,sans-serif;text-align:center';
        document.body.appendChild(el);
      });
    }

    // The error every auth/data call resolves to, so the UI shows a real failure
    // instead of "nothing happening".
    const notConfigured = {
      message: 'Supabase not configured — restart dev server / check .env',
      name: 'SupabaseNotConfigured',
      status: 0,
    };
    const authErr = () => Promise.resolve({ data: { user: null, session: null }, error: notConfigured });

    // Safe no-op client that FAILS LOUDLY on writes/auth (never pretends success).
    const queryResult = Promise.resolve({ data: [], error: notConfigured });
    const chainable: any = {
      select: () => chainable,
      insert: () => chainable,
      update: () => chainable,
      upsert: () => chainable,
      delete: () => chainable,
      eq: () => chainable,
      match: () => chainable,
      order: () => chainable,
      single: () => queryResult,
      maybeSingle: () => queryResult,
      then: (resolve: any, reject: any) => queryResult.then(resolve, reject),
    };
    return {
      from: () => chainable,
      auth: {
        getSession: () => Promise.resolve({ data: { session: null }, error: null }),
        getUser: () => authErr(),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
        signUp: () => authErr(),
        signInWithPassword: () => authErr(),
        signOut: () => Promise.resolve({ error: null }),
      },
      channel: () => ({
        on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
      }),
      removeChannel: () => {},
    } as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

